"""
Generates presentations/MuleSoft-APIGateway-Architecture.pptx

Run:
    pip install --user python-pptx
    python presentations/build_pptx.py

The deck is widescreen (16:9), branded with a blue palette, and self-contained
(no external template). The embedded architecture image is generated by
presentations/diagrams/mulesoft_architecture.py - regenerate that first if
the diagram source changes.
"""

from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn
from copy import deepcopy
from lxml import etree


# -------- Branding / palette --------
NAVY = RGBColor(0x1F, 0x4E, 0x79)
BLUE = RGBColor(0x2E, 0x75, 0xB6)
LIGHT_BLUE = RGBColor(0xDE, 0xEB, 0xF7)
LIGHT_GRAY = RGBColor(0xF2, 0xF2, 0xF2)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
DARK = RGBColor(0x33, 0x33, 0x33)
ORANGE = RGBColor(0xE9, 0x71, 0x32)
GREEN_OK = RGBColor(0x33, 0x99, 0x33)
RED_NO = RGBColor(0xC0, 0x39, 0x2B)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)

OUT_PATH = Path("presentations/MuleSoft-APIGateway-Architecture.pptx")
ARCH_IMG = Path("presentations/img/mulesoft-architecture.png")


# -------- Helpers --------
def set_slide_size(prs):
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H


def add_solid_rect(slide, left, top, width, height, color):
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()
    return shape


def add_text(slide, text, left, top, width, height,
             font_size=14, bold=False, color=DARK, align=PP_ALIGN.LEFT,
             anchor=MSO_ANCHOR.TOP, font_name="Calibri"):
    tb = slide.shapes.add_textbox(left, top, width, height)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.05)
    tf.margin_right = Inches(0.05)
    tf.margin_top = Inches(0.02)
    tf.margin_bottom = Inches(0.02)
    tf.vertical_anchor = anchor

    if isinstance(text, str):
        lines = [text]
    else:
        lines = text

    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = ""  # clear
        run = p.add_run()
        run.text = line
        run.font.name = font_name
        run.font.size = Pt(font_size)
        run.font.bold = bold
        run.font.color.rgb = color
        p.alignment = align
    return tb


def add_bullets(slide, items, left, top, width, height,
                font_size=16, color=DARK, line_spacing=1.15):
    tb = slide.shapes.add_textbox(left, top, width, height)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.05)
    tf.margin_right = Inches(0.05)
    tf.margin_top = Inches(0.05)
    tf.margin_bottom = Inches(0.05)

    for i, text in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = ""
        run = p.add_run()
        run.text = "•  " + text
        run.font.name = "Calibri"
        run.font.size = Pt(font_size)
        run.font.color.rgb = color
        p.alignment = PP_ALIGN.LEFT
        p.line_spacing = line_spacing
        p.space_after = Pt(4)
    return tb


def add_header(slide, title_text, subtitle_text=None):
    # Top navy bar
    add_solid_rect(slide, Inches(0), Inches(0), SLIDE_W, Inches(0.85), NAVY)
    # Title
    add_text(slide, title_text, Inches(0.5), Inches(0.15), Inches(12.3), Inches(0.55),
             font_size=26, bold=True, color=WHITE, anchor=MSO_ANCHOR.MIDDLE)
    if subtitle_text:
        add_text(slide, subtitle_text, Inches(0.5), Inches(0.92), Inches(12.3), Inches(0.35),
                 font_size=13, color=BLUE, anchor=MSO_ANCHOR.TOP)


def add_footer(slide, slide_no, total):
    add_solid_rect(slide, Inches(0), Inches(7.2), SLIDE_W, Inches(0.3), LIGHT_GRAY)
    add_text(slide, "MuleSoft API Gateway Architecture — Citizens-Data APIs",
             Inches(0.4), Inches(7.22), Inches(8), Inches(0.28),
             font_size=10, color=DARK, anchor=MSO_ANCHOR.MIDDLE)
    add_text(slide, f"{slide_no} / {total}",
             Inches(12.0), Inches(7.22), Inches(1.0), Inches(0.28),
             font_size=10, color=DARK, align=PP_ALIGN.RIGHT, anchor=MSO_ANCHOR.MIDDLE)


def make_table(slide, data, left, top, width, height,
               header_row=True, first_col_bold=False,
               header_bg=NAVY, header_fg=WHITE,
               body_bg_alt=LIGHT_GRAY, body_fg=DARK,
               header_font_size=12, body_font_size=11,
               col_widths=None):
    rows = len(data)
    cols = len(data[0])
    tbl_shape = slide.shapes.add_table(rows, cols, left, top, width, height)
    table = tbl_shape.table

    if col_widths is not None:
        total_emu = sum(col_widths)
        scale = width / total_emu if total_emu else 1.0
        for i, w in enumerate(col_widths):
            table.columns[i].width = int(w * scale)

    for r, row in enumerate(data):
        for c, val in enumerate(row):
            cell = table.cell(r, c)
            cell.text = ""  # clear default
            cell.margin_left = Inches(0.08)
            cell.margin_right = Inches(0.08)
            cell.margin_top = Inches(0.04)
            cell.margin_bottom = Inches(0.04)

            is_header = (header_row and r == 0)
            bg = header_bg if is_header else (body_bg_alt if r % 2 == 0 else WHITE)
            fg = header_fg if is_header else body_fg
            font_size = header_font_size if is_header else body_font_size

            cell.fill.solid()
            cell.fill.fore_color.rgb = bg

            tf = cell.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            run = p.add_run()
            run.text = str(val)
            run.font.name = "Calibri"
            run.font.size = Pt(font_size)
            run.font.color.rgb = fg
            run.font.bold = is_header or (first_col_bold and c == 0 and not is_header)
            p.alignment = PP_ALIGN.LEFT
    return table


# -------- Slide builders --------
def slide_title(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    # Full-bleed navy band
    add_solid_rect(s, Inches(0), Inches(0), SLIDE_W, SLIDE_H, WHITE)
    add_solid_rect(s, Inches(0), Inches(2.3), SLIDE_W, Inches(2.4), NAVY)
    # Side accent
    add_solid_rect(s, Inches(0), Inches(4.7), SLIDE_W, Inches(0.12), ORANGE)

    add_text(s, "MuleSoft API Gateway", Inches(0.5), Inches(2.6), Inches(12.3), Inches(0.9),
             font_size=44, bold=True, color=WHITE, anchor=MSO_ANCHOR.MIDDLE)
    add_text(s, "Architecture for Citizens-Data APIs", Inches(0.5), Inches(3.5), Inches(12.3), Inches(0.7),
             font_size=26, color=LIGHT_BLUE, anchor=MSO_ANCHOR.MIDDLE)
    add_text(s, "Federated edge over SaaS, with private connectivity to the on-prem Microsoft integration stack",
             Inches(0.5), Inches(4.95), Inches(12.3), Inches(0.7),
             font_size=16, color=DARK, anchor=MSO_ANCHOR.MIDDLE)

    add_text(s, "Prepared by the Integration Architecture team",
             Inches(0.5), Inches(6.4), Inches(12.3), Inches(0.4),
             font_size=12, color=DARK, anchor=MSO_ANCHOR.MIDDLE)
    add_text(s, "v1.0", Inches(0.5), Inches(6.8), Inches(12.3), Inches(0.3),
             font_size=11, color=BLUE, anchor=MSO_ANCHOR.MIDDLE)
    return s


def slide_synopsis(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Synopsis — Why we are doing this",
               "Problem statement, scope, and the decision drivers")

    bullets = [
        "We need a managed API edge for the new citizens-data APIs — security, rate limiting, observability, contract enforcement.",
        "Orchestration, message transformation, and EDI mediation already run on the existing on-prem Microsoft stack — MuleSoft should NOT replicate that.",
        "Both internal consumers (employees, internal apps) and external consumers (partners, public portals) must hit the same gateway with appropriate policy isolation.",
        "Initial scale: 100,000 calls/day with realistic growth toward 1M+ in 24 months — pick a topology that survives that range.",
        "Hard requirement: API traffic between the gateway and on-prem must NOT traverse the public internet.",
        "Strong preference: SaaS — minimize infrastructure operations burden, inherit MuleSoft's compliance posture (SOC 2, FedRAMP Mod) for citizen data.",
        "Identity federation aligned with corporate IdP (Entra ID / Okta); no second user store.",
    ]
    add_bullets(s, bullets, Inches(0.5), Inches(1.7), Inches(12.3), Inches(5.0),
                font_size=16, color=DARK)

    # Callout box at bottom-left
    add_solid_rect(s, Inches(0.5), Inches(6.55), Inches(12.3), Inches(0.55), LIGHT_BLUE)
    add_text(s, "Bottom line: Anypoint Flex Gateway in Connected mode, on a private MuleSoft-managed cloud space, with private connectivity back to on-prem.",
             Inches(0.7), Inches(6.55), Inches(12.1), Inches(0.55),
             font_size=13, bold=True, color=NAVY, anchor=MSO_ANCHOR.MIDDLE)
    return s


def slide_architecture(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Architecture overview",
               "Federated, dual-listener, private — Anypoint control plane + Private Space data plane")

    # Embed architecture image on the left
    if ARCH_IMG.exists():
        s.shapes.add_picture(str(ARCH_IMG), Inches(0.3), Inches(1.5),
                             width=Inches(8.7), height=Inches(5.4))
    else:
        add_text(s, "[architecture image not generated]", Inches(0.5), Inches(2),
                 Inches(8.5), Inches(2), font_size=14, color=RED_NO)

    # Highlights box on the right
    add_solid_rect(s, Inches(9.2), Inches(1.5), Inches(3.85), Inches(5.4), LIGHT_BLUE)
    add_text(s, "Highlights", Inches(9.35), Inches(1.6), Inches(3.6), Inches(0.4),
             font_size=16, bold=True, color=NAVY)
    highlights = [
        "Anypoint control plane (SaaS) — policy, catalog, monitoring; never sees data path",
        "Private Space data plane — dedicated runtime in MuleSoft-managed cloud",
        "Two listeners: external (WAF + DLB) and internal (private LB) on the same Flex Gateway",
        "JWT for external, mTLS for internal — separate policy bundles",
        "Private connectivity (ExpressRoute or Direct Connect) — no public internet on data path",
        "Independent IdP federation — Entra ID / Okta",
        "Dual-shipped observability — Anypoint + Splunk + Datadog",
    ]
    add_bullets(s, highlights, Inches(9.3), Inches(2.05), Inches(3.7), Inches(4.8),
                font_size=11, color=DARK, line_spacing=1.10)
    return s


def slide_product(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Recommended product — Anypoint Flex Gateway (Connected mode)",
               "Why Flex Gateway, not full Mule runtime")

    bullets = [
        "Purpose-built API gateway — Envoy proxy core wrapped with MuleSoft's policy framework. Not a full integration runtime forced into a gateway role.",
        "Lightweight runtime — about 50 MB process footprint vs about 1 GB for a Mule runtime worker. Cold start under 5 seconds.",
        "Single-digit millisecond overhead per request with the full security policy chain attached (JWT + rate limit + schema validation).",
        "Hot policy reload — change a policy in API Manager and it goes live in seconds, no restart, no traffic drop.",
        "Cloud-agnostic single binary — runs on Linux, Docker, EKS, AKS, OpenShift, or CloudHub 2.0. Same image everywhere.",
        "Centrally managed from Anypoint Platform — policy catalog, SLA tiers, analytics, audit log — without writing your own control plane.",
    ]
    add_bullets(s, bullets, Inches(0.5), Inches(1.7), Inches(12.3), Inches(4.0),
                font_size=15, color=DARK)

    # Why-for-us callout
    add_solid_rect(s, Inches(0.5), Inches(6.0), Inches(12.3), Inches(1.05), LIGHT_BLUE)
    add_text(s, "Why this for us",
             Inches(0.7), Inches(6.05), Inches(3.0), Inches(0.4),
             font_size=15, bold=True, color=NAVY)
    add_text(s,
             "Gateway-only role (MS stack does orchestration / transformation / EDI) + private-cloud requirement + SaaS preference + citizen-data sensitivity = Flex Gateway in Connected mode on a Private Space is the lowest-friction, lowest-ops fit.",
             Inches(0.7), Inches(6.42), Inches(12.0), Inches(0.6),
             font_size=12, color=DARK, anchor=MSO_ANCHOR.TOP)
    return s


def slide_flex_vs_mule(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Flex Gateway vs Full Mule Runtime — side by side",
               "Same vendor, very different products; pick the role that fits")

    data = [
        ["Aspect", "Anypoint Flex Gateway", "Full Mule Runtime"],
        ["Primary role", "API gateway / edge proxy", "Integration runtime + API gateway"],
        ["Core technology", "Envoy proxy (CNCF, battle-tested)", "JVM-based Mule engine"],
        ["Footprint per replica", "~50 MB process", "~1 GB JVM worker"],
        ["Cold start", "< 5 seconds", "30–60 seconds"],
        ["Per-request overhead (full policies)", "Single-digit ms", "10–30 ms"],
        ["DataWeave transformation", "Not available (by design)", "Native, first-class"],
        ["Orchestration / Flows / connectors", "Not available", "Full capability"],
        ["Custom logic extensibility", "WebAssembly filters (Rust / Go / AssemblyScript)", "Java + Groovy + DataWeave"],
        ["Policy hot reload (no restart)", "Yes", "Limited — often requires app redeploy"],
        ["Deployment substrate", "Linux / Docker / K8s / CloudHub 2.0", "CloudHub / Runtime Fabric / on-prem JVM"],
        ["Pricing per replica", "Lower (smaller vCore consumption)", "Higher"],
        ["Best fit for our scope", "✔  Pure API edge — our chosen role", "Overkill when no integration logic is needed"],
    ]
    make_table(s, data, Inches(0.4), Inches(1.55), Inches(12.5), Inches(5.45),
               header_bg=NAVY, header_fg=WHITE, header_font_size=13, body_font_size=11,
               col_widths=[Inches(3.5), Inches(4.5), Inches(4.5)])
    return s


def slide_network(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Network — no public internet on data path",
               "Components to provision for fully private connectivity, internal + external")

    data = [
        ["Component", "Provisioned by", "Purpose"],
        ["CloudHub 2.0 Private Space (centralus or AWS region)", "MuleSoft", "Dedicated runtime VPC/VNet for the Flex Gateway data plane"],
        ["Anypoint Dedicated Load Balancer (DLB)", "MuleSoft", "Public custom domain + TLS termination for external listener"],
        ["Anypoint Security Edge (WAF + DDoS)", "MuleSoft", "Threat protection on the external listener"],
        ["Internal Load Balancer (private only)", "MuleSoft + Customer DNS", "Internal listener reachable only via private network"],
        ["ExpressRoute Private Peering (Azure) OR Direct Connect + Transit Gateway (AWS)", "Customer + Carrier", "Primary private link from MuleSoft cloud to on-prem"],
        ["Site-to-Site IPsec VPN over ER Microsoft Peering / DX Public VIF", "Customer", "Warm failover path — encrypted, also private"],
        ["VNet peering (Azure) or VPC/TGW peering (AWS) to MuleSoft Private Space", "Customer", "Network adjacency between customer cloud and MuleSoft cloud"],
        ["Customer-side ExpressRoute Gateway / Transit Gateway", "Customer Network Team", "BGP termination of the private circuit"],
        ["Private DNS zone link into MuleSoft Private Space", "Customer", "Backend hostname resolution (e.g. biztalk-prod.internal.yourco)"],
        ["TLS / mTLS certificates (public CA + internal CA)", "Customer PKI", "Edge TLS, mTLS for internal listener, mTLS to backend"],
        ["Firewall rules — allow Private Space CIDR → MS stack on 443", "Customer Network Team", "Inbound to on-prem from the gateway only"],
        ["Splunk HEC private endpoint + Datadog Agent in VPC", "Customer", "Observability dual-ship without leaving the private network"],
    ]
    make_table(s, data, Inches(0.3), Inches(1.55), Inches(12.7), Inches(5.45),
               header_bg=NAVY, header_fg=WHITE, header_font_size=12, body_font_size=10,
               col_widths=[Inches(5.0), Inches(3.0), Inches(4.7)])
    return s


def slide_capacity(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Capacity planning — 100K calls/day",
               "Traffic math, replica sizing, headroom, and indicative cost")

    # Traffic math table — left half
    add_text(s, "Traffic math", Inches(0.5), Inches(1.55), Inches(6), Inches(0.4),
             font_size=15, bold=True, color=NAVY)
    traffic = [
        ["Metric", "Value"],
        ["Daily volume", "100,000 calls"],
        ["Average TPS (24h)", "~1.16"],
        ["Business-hours avg TPS (8h concentration)", "~3.5"],
        ["Peak TPS (5× business average)", "~17"],
        ["Worst-case spike (10× business average)", "~35"],
        ["Headroom over peak with recommended config", "≈ 10×"],
    ]
    make_table(s, traffic, Inches(0.5), Inches(1.95), Inches(6.1), Inches(2.6),
               header_bg=NAVY, header_fg=WHITE, header_font_size=12, body_font_size=11,
               col_widths=[Inches(4.0), Inches(2.1)])

    # Recommended config table — right half
    add_text(s, "Recommended configuration", Inches(6.85), Inches(1.55), Inches(6.3), Inches(0.4),
             font_size=15, bold=True, color=NAVY)
    config = [
        ["Setting", "Value"],
        ["CH 2.0 deployment size", "0.1 vCore per replica"],
        ["Replica count", "2 (multi-AZ)"],
        ["Auto-scaling", "Enabled — min 2 / max 4"],
        ["Scale trigger", "CPU > 60% over 5 min"],
        ["Anypoint DLB", "1 (shared by both listeners)"],
        ["Security Edge (WAF)", "On — external listener only"],
        ["Anypoint Monitoring tier", "Standard"],
    ]
    make_table(s, config, Inches(6.85), Inches(1.95), Inches(6.1), Inches(2.95),
               header_bg=NAVY, header_fg=WHITE, header_font_size=12, body_font_size=11,
               col_widths=[Inches(3.6), Inches(2.5)])

    # Cost callout — bottom full width
    add_solid_rect(s, Inches(0.5), Inches(5.0), Inches(12.5), Inches(1.85), LIGHT_BLUE)
    add_text(s, "Indicative monthly cost (list pricing)",
             Inches(0.7), Inches(5.1), Inches(8), Inches(0.4),
             font_size=15, bold=True, color=NAVY)

    cost = [
        ["Line item", "Monthly (approx)"],
        ["2× Flex Gateway replicas @ 0.1 vCore", "$400 – $800"],
        ["Private Space base fee", "$1,500 – $3,000"],
        ["Dedicated Load Balancer", "$250"],
        ["Anypoint Monitoring (Standard)", "$200 – $500"],
        ["Data transfer (low at this volume)", "~$50"],
        ["Total (list, gateway-tier only)", "≈ $2,400 – $4,600 / mo"],
    ]
    make_table(s, cost, Inches(0.7), Inches(5.55), Inches(12.1), Inches(1.25),
               header_bg=BLUE, header_fg=WHITE, header_font_size=11, body_font_size=10,
               col_widths=[Inches(8.0), Inches(4.1)])

    add_text(s, "Note: list price is the ceiling; enterprise discount typically reduces by 30–50%. ExpressRoute / Direct Connect costs are absorbed by existing network OpEx.",
             Inches(0.5), Inches(6.85), Inches(12.3), Inches(0.3),
             font_size=10, color=DARK)
    return s


def slide_azure_vs_aws(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Azure-native vs AWS-native Private Spaces",
               "Same Anypoint product, two cloud substrates — pick by network adjacency")

    data = [
        ["Dimension", "Azure-resident (centralus)", "AWS-resident (us-east-* / us-west-*)"],
        ["Cloud provider underneath", "Microsoft Azure (centralus, Iowa)", "Amazon Web Services"],
        ["Paired DR region (Anypoint-native)", "eastus2 (Virginia)", "Customer choice (e.g. us-west-2)"],
        ["Hybrid connectivity primitive", "ExpressRoute (Private Peering)", "Direct Connect + Transit Gateway"],
        ["Customer cloud account required?", "No — VNet peering is the path", "Yes — AWS account needed for TGW peering"],
        ["Backup connectivity", "IPsec VPN over ER Microsoft Peering", "IPsec VPN over public internet OR DX Public VIF"],
        ["IdP affinity (corporate fit)", "Entra ID native — seamless", "IAM / Cognito native — fine but separate"],
        ["Feature parity status", "Catching up — confirm GA per region", "Reference implementation (most features land here first)"],
        ["Anypoint Security Edge (WAF) GA?", "Verify with MuleSoft sales", "GA"],
        ["Customer-managed keys (CMK)", "Verify availability (enterprise add-on)", "Verify availability (enterprise add-on)"],
        ["Pricing meters", "Per-vCore + ExpressRoute egress", "Per-vCore + DX data transfer"],
        ["Best fit when…", "MS stack runs in Azure; you already use ExpressRoute; Entra-first identity", "AWS-native stack; existing DX presence; need newest features first"],
        ["Risk to flag", "Regional GA + feature parity gaps", "Need to stand up + operate an AWS account just for peering"],
    ]
    make_table(s, data, Inches(0.3), Inches(1.55), Inches(12.7), Inches(5.45),
               header_bg=NAVY, header_fg=WHITE, header_font_size=12, body_font_size=10,
               col_widths=[Inches(3.5), Inches(4.6), Inches(4.6)])
    return s


def slide_risks_and_next(prs):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    add_header(s, "Risks & next steps",
               "What we still need to verify and how we get to go-live")

    # Risks (left column)
    add_text(s, "Key risks", Inches(0.5), Inches(1.55), Inches(6), Inches(0.4),
             font_size=16, bold=True, color=RED_NO)
    risks = [
        "Citizen data residency & compliance — requires DPA, possibly BAA, plus the full controls bundle (doc 07).",
        "Azure Private Space feature parity vs AWS — confirm Security Edge, custom DLB, CMK with MuleSoft account team.",
        "MuleSoft personnel privileged access — agree memory-dump policy (consent-based, named approvers).",
        "Vendor lock-in — Anypoint policy format + WASM SDK are MuleSoft-specific.",
        "Auto-scale latency on CH 2.0 ~1–2 min — mitigate with spike-control policy.",
        "Talent: Flex Gateway specialists are scarcer than general MuleSoft developers — plan ramp-up.",
    ]
    add_bullets(s, risks, Inches(0.5), Inches(1.95), Inches(6.2), Inches(5.0),
                font_size=12, color=DARK, line_spacing=1.15)

    # Next steps (right column)
    add_text(s, "Next steps", Inches(7.0), Inches(1.55), Inches(6), Inches(0.4),
             font_size=16, bold=True, color=GREEN_OK)
    steps = [
        "Engage MuleSoft account team — confirm centralus Private Space GA, feature matrix, pricing for our scale.",
        "Open DPA / BAA conversation immediately — these are slow.",
        "Pre-go-live security checklist (doc 07 §12) as tabletop with CISO / DPO.",
        "Define IdP-side configuration with the IAM team — clients, scopes, claim shape.",
        "Network team starts the ExpressRoute / Transit Gateway change request — 2–3 week lead time.",
        "Stand up POC in a dev Private Space; validate one API end-to-end including private connectivity, mTLS, JWT.",
        "Decide observability stack (Splunk + Datadog) and provision private endpoints into the Private Space.",
    ]
    add_bullets(s, steps, Inches(7.0), Inches(1.95), Inches(6.0), Inches(5.0),
                font_size=12, color=DARK, line_spacing=1.15)
    return s


# -------- Main --------
def main():
    prs = Presentation()
    set_slide_size(prs)

    builders = [
        slide_title,
        slide_synopsis,
        slide_architecture,
        slide_product,
        slide_flex_vs_mule,
        slide_network,
        slide_capacity,
        slide_azure_vs_aws,
        slide_risks_and_next,
    ]
    total = len(builders)
    slides = []
    for i, build in enumerate(builders, start=1):
        s = build(prs)
        # Title slide has no footer
        if i != 1:
            add_footer(s, i, total)
        slides.append(s)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    prs.save(OUT_PATH)
    print(f"OK: wrote {OUT_PATH} with {len(slides)} slides")


if __name__ == "__main__":
    main()
